project_name: pd-report

builds:
  - main: ./main.go
    binary: pd-report
    goarch:
      - amd64
    goos:
      - windows
      - darwin
      - linux
    env:
      - CGO_ENABLED=0

archives:
  -
    format: tar.gz
    files:
      - LICENSE
