project_name: pd-report

builds:
  - main: ./main.go
    binary: pd-report
    goarch:
      - amd64
    goos:
      - windows
      - darwin
      - linux
    env:
      - CGO_ENABLED=0

archives:
  -
    format: tar.gz
    files:
      - LICENSE

brews:
  -
    name: pd-report
    tap:
      owner: form3tech-oss
      name: homebrew-tap
    folder: Formula
    commit_author:
      name: AntonioRodrigues
      email: roger.sole@form3.tech

    homepage: "https://github.com/form3tech-oss/go-pagerduty-oncall-report/"
    description: "Get a report of oncall rotations from your PagerDuty account"

