language: go
go: '1.14'
script:
- make ci
after_success:
- make embed-assets
- bash <(curl -s https://codecov.io/bash)
notifications:
  email: false
deploy:
- provider: script
  skip_cleanup: true
  script: curl -sL http://git.io/goreleaser | bash
  on:
    tags: true
env:
  global:
    secure: PGaYS9ATDRWueeHeRdP+dAbyAFQS56louL7dJBwVP0QXOP0FcTxs+VPt2rqTMj2UYENWNIxa1EOcY50o/3Lno22gH0lvZnU3Ia1echOTRsuhfnsROw0q13B4+TyCXQ6X7btYKukbrmWsE/ab9BrYCo2Or+kVd0l/J56bS/+vOaZcwvDkAniVcRQPkg1fUinMCPn+z+WqxA4Lzjs2ilW8VjyjaZizNh96KWArWtsihFwN4CC4EfznxB3st52b7r8OpKIBv2dKGrrgnvfkU05rGMzm8nNzYJdo1Dm7zQKge4J2VPyZ3NL7nK3fw+pDABDACeHVM8zFTQ7PEuxxmW79tpTwzbq2tdngFphFlHObxbztTVsL0q0LlyNFd9Lb4QZK7l3ShEXo/i3dy4FZYKaGCPrIO75TKdn2Zjd1MbQwRCoLIFGnzgN/pUkMZup4t4ycDp1G/jw2E/BVcoXgjN5xYgkofn1a0cscO0S4GLssVjIrlM3ukjo/yPx+Ya0sksOzp81w0mRwhGoFEeys50aSr+ZGZZQqaHyTlQSy0lHtJx7gUzaCVhLn3AwaJkZzAYCdnRAFISUnbgyS1cTb/UxxiHp8mYYupZ58Dh+ITVTU7vJXLn7w3utn9MjK1yvw/WF3e+vb1vwxYA/sTXoVdGeyLhDhF1I4BA9dNJm5uttnkCE=
